services:
  - type: web
    name: whu-walker
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 60 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: AMAP_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.deepseek.com/v1
      - key: LLM_MODEL
        value: deepseek-chat
    autoDeploy: true
