# fly.toml app configuration file generated for whu-walker
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'whu-walker'
primary_region = 'sin'

[build]

[env]
  FLASK_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
